format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$golang\
$helm\
$nim\
$nodejs\
$python\
$terraform\
$memory_usage\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[directory]
truncation_length = 1

[git_branch]
# replace "on" with "⭑"
format = "⭑ [$symbol$branch]($style) "

[python]
# replace "via" with "⮕"
format = '⮕ [${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '

[terraform]
# replace "via" with "⮕"
format = '⮕ [$symbol$workspace]($style) '
